language: cpp
dist: bionic
sudo: required
cache:
  ccache: true
compiler:
- clang
- gcc
env:
  global:
  - secure: "SnIBG/xLIHX3CSvUbqqsX8xTVqIqQ7fFS6HWO6KZQVBsT6yugTwYHbyhNiU531JejYJ/I3ZrDhXfYH3qFZiYxnH1sifvwV+fnTtMXpPN7qPZwIymkjcmm6gJF51e0C7VOfUbvKFv0ngwj+ul21rgZSMuoEvxPK0WxtE3/ZSfn9c="
  - APT_DEPENDENCIES="doxygen doxygen-latex libboost-all-dev libeigen3-dev liblapack-dev libblas-dev gfortran python3-dev python3-sphinx"
  - DEBSIGN_KEYID=5AE5CD75
  - CMAKE_ADDITIONAL_OPTIONS="-DPYTHON_EXECUTABLE=/usr/bin/python3"
notifications:
  email:
  - hpp-source@laas.fr
branches:
  only:
  - disabled_travis_because_not_relevant_anymore
matrix:
  allow_failures:
  - compiler: clang
before_install: ./travis_custom/custom_before_install
script:
  - sudo free -m -t
  - ./.travis/run ../travis_custom/custom_build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
