sot-core: sot::BinaryOp< Tin1, Tin2, Tout, Operator > Class Template Reference
sot::BinaryOp< Tin1, Tin2, Tout, Operator > Class Template Reference
#include <sot-core/binary-op.h>
Public Member Functions
BinaryOp (const std::string &name)
virtual ~BinaryOp (void)
virtual void commandLine (const std::string &cmdLine, std::istringstream &cmdArgs, std::ostream &os)
Static Public Member Functions
static std::string getTypeIn1Name (void)
static std::string getTypeIn2Name (void)
static std::string getTypeOutName (void)
Public Attributes
dg::SignalPtr< Tin1, int > SIN1
dg::SignalPtr< Tin2, int > SIN2
dg::SignalTimeDependent< Tout,
int > SOUT
Static Public Attributes
static const std::string CLASS_NAME
Protected Member Functions
Tout & computeOperation (Tout &res, int time)
template<class Tin1, class Tin2, class Tout, typename Operator>
class sot::BinaryOp< Tin1, Tin2, Tout, Operator >
Constructor & Destructor Documentation
template<class Tin1 , class Tin2 , class Tout , typename Operator > sot::BinaryOp< Tin1, Tin2, Tout, Operator >::BinaryOp (const std::string & name) [inline]
References sot::BinaryOp< Tin1, Tin2, Tout, Operator >::getTypeIn1Name().
template<class Tin1 , class Tin2 , class Tout , typename Operator > virtual sot::BinaryOp< Tin1, Tin2, Tout, Operator >::~BinaryOp (void) [inline, virtual]
Member Function Documentation
template<class Tin1 , class Tin2 , class Tout , typename Operator > virtual void sot::BinaryOp< Tin1, Tin2, Tout, Operator >::commandLine (const std::string & cmdLine, std::istringstream & cmdArgs, std::ostream & os) [virtual]
Reimplemented from dynamicgraph::Entity.
template<class Tin1 , class Tin2 , class Tout , typename Operator > Tout& sot::BinaryOp< Tin1, Tin2, Tout, Operator >::computeOperation (Tout & res, int time) [inline, protected]
References dynamicgraph::Entity::signalRegistration(), sot::BinaryOp< Tin1, Tin2, Tout, Operator >::SIN1, sot::BinaryOp< Tin1, Tin2, Tout, Operator >::SIN2, and sot::BinaryOp< Tin1, Tin2, Tout, Operator >::SOUT.
template<class Tin1 , class Tin2 , class Tout , typename Operator > static std::string sot::BinaryOp< Tin1, Tin2, Tout, Operator >::getTypeIn1Name (void) [inline, static]
Referenced by sot::BinaryOp< Tin1, Tin2, Tout, Operator >::BinaryOp().
template<class Tin1 , class Tin2 , class Tout , typename Operator > static std::string sot::BinaryOp< Tin1, Tin2, Tout, Operator >::getTypeIn2Name (void) [inline, static]
template<class Tin1 , class Tin2 , class Tout , typename Operator > static std::string sot::BinaryOp< Tin1, Tin2, Tout, Operator >::getTypeOutName (void) [inline, static]
Member Data Documentation
template<class Tin1 , class Tin2 , class Tout , typename Operator > const std::string sot::BinaryOp< Tin1, Tin2, Tout, Operator >::CLASS_NAME [static]
Reimplemented from dynamicgraph::Entity.
template<class Tin1 , class Tin2 , class Tout , typename Operator > dg::SignalPtr<Tin1,int> sot::BinaryOp< Tin1, Tin2, Tout, Operator >::SIN1
Referenced by sot::BinaryOp< Tin1, Tin2, Tout, Operator >::computeOperation().
template<class Tin1 , class Tin2 , class Tout , typename Operator > dg::SignalPtr<Tin2,int> sot::BinaryOp< Tin1, Tin2, Tout, Operator >::SIN2
Referenced by sot::BinaryOp< Tin1, Tin2, Tout, Operator >::computeOperation().
template<class Tin1 , class Tin2 , class Tout , typename Operator > dg::SignalTimeDependent<Tout,int> sot::BinaryOp< Tin1, Tin2, Tout, Operator >::SOUT
Referenced by sot::BinaryOp< Tin1, Tin2, Tout, Operator >::computeOperation().