dynamicgraph::sot::MatrixHomogeneous Class Reference
dynamicgraph::sot::MatrixHomogeneous Class Reference
#include <sot/core/matrix-homogeneous.hh>
Public Member Functions
MatrixHomogeneous (void)
MatrixHomogeneous (const ml::Matrix &copy)
virtual ~MatrixHomogeneous (void)
MatrixHomogeneous & buildFrom (const MatrixRotation &rot, const ml::Vector &trans)
ml::Matrix & extract (ml::Matrix &rot) const
MatrixRotation & extract (MatrixRotation &rot) const
ml::Vector & extract (ml::Vector &trans) const
MatrixHomogeneous operator* (const MatrixHomogeneous &h) const
MatrixHomogeneous & operator= (const ml::Matrix &)
MatrixHomogeneous & inverse (MatrixHomogeneous &invMatrix) const
MatrixHomogeneous inverse (void) const
ml::Vector & multiply (const ml::Vector &v1, ml::Vector &res) const
ml::Vector multiply (const ml::Vector &v1) const
Constructor & Destructor Documentation
dynamicgraph::sot::MatrixHomogeneous::MatrixHomogeneous (void)
dynamicgraph::sot::MatrixHomogeneous::MatrixHomogeneous (const ml::Matrix & copy)
virtual dynamicgraph::sot::MatrixHomogeneous::~MatrixHomogeneous (void) [inline, virtual]
Member Function Documentation
MatrixHomogeneous& dynamicgraph::sot::MatrixHomogeneous::buildFrom (const MatrixRotation & rot, const ml::Vector & trans)
ml::Matrix& dynamicgraph::sot::MatrixHomogeneous::extract (ml::Matrix & rot) const
MatrixRotation& dynamicgraph::sot::MatrixHomogeneous::extract (MatrixRotation & rot) const
ml::Vector& dynamicgraph::sot::MatrixHomogeneous::extract (ml::Vector & trans) const
MatrixHomogeneous& dynamicgraph::sot::MatrixHomogeneous::inverse (MatrixHomogeneous & invMatrix) const
MatrixHomogeneous dynamicgraph::sot::MatrixHomogeneous::inverse (void) const [inline]
Reimplemented from maal::boost::Matrix.
References inverse().
Referenced by inverse().
ml::Vector& dynamicgraph::sot::MatrixHomogeneous::multiply (const ml::Vector & v1, ml::Vector & res) const
Reimplemented from maal::boost::Matrix.
ml::Vector dynamicgraph::sot::MatrixHomogeneous::multiply (const ml::Vector & v1) const [inline]
Reimplemented from maal::boost::Matrix.
References multiply().
Referenced by multiply().
MatrixHomogeneous dynamicgraph::sot::MatrixHomogeneous::operator* (const MatrixHomogeneous & h) const
MatrixHomogeneous& dynamicgraph::sot::MatrixHomogeneous::operator= (const ml::Matrix &)
Reimplemented from maal::boost::Matrix.