dynamicgraph::sot::detail::circular_buffer< T > Class Template Reference
dynamicgraph::sot::detail::circular_buffer< T > Class Template Reference
#include <sot/core/fir-filter.hh>
Public Member Functions
circular_buffer ()
void push_front (const T &data)
void reset_capacity (size_t n)
void reset_capacity (size_t n, const T &el)
T & operator[] (size_t i)
size_t size () const
template<class T>
class dynamicgraph::sot::detail::circular_buffer< T >
Constructor & Destructor Documentation
template<class T> dynamicgraph::sot::detail::circular_buffer< T >::circular_buffer () [inline]
Member Function Documentation
template<class T> T& dynamicgraph::sot::detail::circular_buffer< T >::operator[] (size_t i) [inline]
template<class T> void dynamicgraph::sot::detail::circular_buffer< T >::push_front (const T & data) [inline]
Referenced by dynamicgraph::sot::FIRFilter< sigT, coefT >::compute().
template<class T> void dynamicgraph::sot::detail::circular_buffer< T >::reset_capacity (size_t n) [inline]
Referenced by dynamicgraph::sot::FIRFilter< sigT, coefT >::resizeBuffer().
template<class T> void dynamicgraph::sot::detail::circular_buffer< T >::reset_capacity (size_t n, const T & el) [inline]
template<class T> size_t dynamicgraph::sot::detail::circular_buffer< T >::size (void) const [inline]
Referenced by dynamicgraph::sot::FIRFilter< sigT, coefT >::compute().