sot-core: sot::GainHyperbolic Class Reference
sot::GainHyperbolic Class Reference
#include <sot-core/gain-hyperbolic.h>
Public Member Functions
virtual void display (std::ostream &os) const
virtual const std::string & getClassName (void) const
GainHyperbolic (const std::string &name)
GainHyperbolic (const std::string &name, const double &lambda)
GainHyperbolic (const std::string &name, const double &valueAt0, const double &valueAtInfty, const double &tanAt0, const double &decal0)
void init (void)
void init (const double &lambda)
void init (const double &valueAt0, const double &valueAtInfty, const double &tanAt0, const double &decal0)
void forceConstant (void)
virtual void commandLine (const std::string &cmdLine, std::istringstream &cmdArgs, std::ostream &os)
Public Attributes
dg::SignalPtr< ml::Vector, int > errorSIN
dg::SignalTimeDependent
< double, int > gainSOUT
Static Public Attributes
static const double ZERO_DEFAULT
static const double INFTY_DEFAULT
static const double TAN_DEFAULT
static const std::string CLASS_NAME
Protected Member Functions
double & computeGain (double &res, int t)
Protected Attributes
double coeff_a
double coeff_b
double coeff_c
double coeff_d
Constructor & Destructor Documentation
sot::GainHyperbolic::GainHyperbolic (const std::string & name)
sot::GainHyperbolic::GainHyperbolic (const std::string & name, const double & lambda)
sot::GainHyperbolic::GainHyperbolic (const std::string & name, const double & valueAt0, const double & valueAtInfty, const double & tanAt0, const double & decal0)
Member Function Documentation
virtual void sot::GainHyperbolic::commandLine (const std::string & cmdLine, std::istringstream & cmdArgs, std::ostream & os) [virtual]
Reimplemented from dynamicgraph::Entity.
double& sot::GainHyperbolic::computeGain (double & res, int t) [protected]
virtual void sot::GainHyperbolic::display (std::ostream & os) const [virtual]
Reimplemented from dynamicgraph::Entity.
void sot::GainHyperbolic::forceConstant (void)
virtual const std::string& sot::GainHyperbolic::getClassName (void) const [inline, virtual]
Reimplemented from dynamicgraph::Entity.
void sot::GainHyperbolic::init (const double & lambda) [inline]
References init().
Referenced by init().
void sot::GainHyperbolic::init (void) [inline]
References init().
Referenced by init().
void sot::GainHyperbolic::init (const double & valueAt0, const double & valueAtInfty, const double & tanAt0, const double & decal0)
Member Data Documentation
const std::string sot::GainHyperbolic::CLASS_NAME [static]
Reimplemented from dynamicgraph::Entity.
double sot::GainHyperbolic::coeff_a [protected]
double sot::GainHyperbolic::coeff_b [protected]
double sot::GainHyperbolic::coeff_c [protected]
double sot::GainHyperbolic::coeff_d [protected]
dg::SignalPtr<ml::Vector,int> sot::GainHyperbolic::errorSIN
dg::SignalTimeDependent<double,int> sot::GainHyperbolic::gainSOUT
const double sot::GainHyperbolic::INFTY_DEFAULT [static]
const double sot::GainHyperbolic::TAN_DEFAULT [static]
const double sot::GainHyperbolic::ZERO_DEFAULT [static]