sot-core: sot::MatrixHomogeneous Class Reference
sot::MatrixHomogeneous Class Reference
#include <sot-core/matrix-homogeneous.h>
Public Member Functions
MatrixHomogeneous (void)
~MatrixHomogeneous (void)
MatrixHomogeneous & buildFrom (const MatrixRotation &rot, const ml::Vector &trans)
ml::Matrix & extract (ml::Matrix &rot) const
MatrixRotation & extract (MatrixRotation &rot) const
ml::Vector & extract (ml::Vector &trans) const
MatrixHomogeneous & operator= (const ml::Matrix &)
MatrixHomogeneous & inverse (MatrixHomogeneous &invMatrix) const
MatrixHomogeneous inverse (void) const
ml::Vector & multiply (const ml::Vector &v1, ml::Vector &res) const
ml::Vector multiply (const ml::Vector &v1) const
Constructor & Destructor Documentation
sot::MatrixHomogeneous::MatrixHomogeneous (void) [inline]
sot::MatrixHomogeneous::~MatrixHomogeneous (void) [inline]
Member Function Documentation
MatrixHomogeneous& sot::MatrixHomogeneous::buildFrom (const MatrixRotation & rot, const ml::Vector & trans)
ml::Vector& sot::MatrixHomogeneous::extract (ml::Vector & trans) const
MatrixRotation& sot::MatrixHomogeneous::extract (MatrixRotation & rot) const
ml::Matrix& sot::MatrixHomogeneous::extract (ml::Matrix & rot) const
MatrixHomogeneous sot::MatrixHomogeneous::inverse (void) const [inline]
Reimplemented from maal::boost::Matrix.
References inverse().
Referenced by inverse().
MatrixHomogeneous& sot::MatrixHomogeneous::inverse (MatrixHomogeneous & invMatrix) const
ml::Vector sot::MatrixHomogeneous::multiply (const ml::Vector & v1) const [inline]
Reimplemented from maal::boost::Matrix.
References multiply().
Referenced by multiply().
ml::Vector& sot::MatrixHomogeneous::multiply (const ml::Vector & v1, ml::Vector & res) const
Reimplemented from maal::boost::Matrix.
MatrixHomogeneous& sot::MatrixHomogeneous::operator= (const ml::Matrix &)
Reimplemented from maal::boost::Matrix.