dynamicgraph::sot::IntegratorAbstract< sigT, coefT > Class Template Reference
dynamicgraph::sot::IntegratorAbstract< sigT, coefT > Class Template Reference
integrates an ODE. If Y is the output and X the input, the following equation is integrated: a_p * d(p)Y / dt^p + .... + a_0 Y = b_m * d(m)X / dt^m + ... . b_0 X a_i are the coefficients of the denominator of the associated transfer function between X and Y, while the b_i are those of the numerator.
#include <sot/core/integrator-abstract.hh>
Public Member Functions
virtual const std::string & getClassName () const
IntegratorAbstract (const std::string &name)
virtual ~IntegratorAbstract ()
virtual sigT & integrate (sigT &res, int time)=0
virtual void commandLine (const std::string &cmdLine, std::istringstream &cmdArgs, std::ostream &os)
void pushNumCoef (const coefT &numCoef)
void pushDenomCoef (const coefT &denomCoef)
void popNumCoef ()
void popDenomCoef ()
Static Public Member Functions
static std::string getTypeName (void)
Public Attributes
dg::SignalPtr< sigT, int > SIN
dg::SignalTimeDependent< sigT,
int > SOUT
Static Public Attributes
static const std::string CLASS_NAME
Protected Attributes
std::vector< coefT > numerator
std::vector< coefT > denominator
Detailed Description
template<class sigT, class coefT>
class dynamicgraph::sot::IntegratorAbstract< sigT, coefT >
integrates an ODE. If Y is the output and X the input, the following equation is integrated: a_p * d(p)Y / dt^p + .... + a_0 Y = b_m * d(m)X / dt^m + ... . b_0 X a_i are the coefficients of the denominator of the associated transfer function between X and Y, while the b_i are those of the numerator.
Constructor & Destructor Documentation
template<class sigT , class coefT > dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::IntegratorAbstract (const std::string & name) [inline]
References dynamicgraph::Entity::signalRegistration(), dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::SIN, and dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::SOUT.
template<class sigT , class coefT > virtual dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::~IntegratorAbstract () [inline, virtual]
Member Function Documentation
template<class sigT , class coefT > virtual void dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::commandLine (const std::string & cmdLine, std::istringstream & cmdArgs, std::ostream & os) [inline, virtual]
Reimplemented from dynamicgraph::Entity.
References dynamicgraph::Signal< T, Time >::accessCopy(), dynamicgraph::PoolStorage::getEntity(), dynamicgraph::PoolStorage::getInstance(), dynamicgraph::Entity::getSignal(), dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::popDenomCoef(), dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::popNumCoef(), dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::pushDenomCoef(), and dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::pushNumCoef().
template<class sigT , class coefT > virtual const std::string& dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::getClassName (void) const [inline, virtual]
Implements dynamicgraph::Entity.
Reimplemented in dynamicgraph::sot::IntegratorEuler< sigT, coefT >.
template<class sigT , class coefT > static std::string dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::getTypeName (void) [inline, static]
Reimplemented in dynamicgraph::sot::IntegratorEuler< sigT, coefT >.
template<class sigT , class coefT > virtual sigT& dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::integrate (sigT & res, int time) [pure virtual]
Implemented in dynamicgraph::sot::IntegratorEuler< sigT, coefT >.
template<class sigT , class coefT > void dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::popDenomCoef () [inline]
References dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::denominator.
Referenced by dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::commandLine().
template<class sigT , class coefT > void dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::popNumCoef () [inline]
References dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::numerator.
Referenced by dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::commandLine().
template<class sigT , class coefT > void dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::pushDenomCoef (const coefT & denomCoef) [inline]
References dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::denominator.
Referenced by dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::commandLine().
template<class sigT , class coefT > void dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::pushNumCoef (const coefT & numCoef) [inline]
References dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::numerator.
Referenced by dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::commandLine().
Member Data Documentation
template<class sigT , class coefT > const std::string dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::CLASS_NAME [static]
Reimplemented in dynamicgraph::sot::IntegratorEuler< sigT, coefT >.
template<class sigT , class coefT > std::vector<coefT> dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::denominator [protected]
Referenced by dynamicgraph::sot::IntegratorEuler< sigT, coefT >::integrate(), dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::popDenomCoef(), and dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::pushDenomCoef().
template<class sigT , class coefT > std::vector<coefT> dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::numerator [protected]
Referenced by dynamicgraph::sot::IntegratorEuler< sigT, coefT >::integrate(), dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::popNumCoef(), and dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::pushNumCoef().
template<class sigT , class coefT > dg::SignalPtr<sigT, int> dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::SIN
Referenced by dynamicgraph::sot::IntegratorEuler< sigT, coefT >::integrate(), dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::IntegratorAbstract(), and dynamicgraph::sot::IntegratorEuler< sigT, coefT >::IntegratorEuler().
template<class sigT , class coefT > dg::SignalTimeDependent<sigT, int> dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::SOUT
Referenced by dynamicgraph::sot::IntegratorAbstract< sigT, coefT >::IntegratorAbstract(), and dynamicgraph::sot::IntegratorEuler< sigT, coefT >::IntegratorEuler().