sot-core: sotRotationComposed Class Reference
sotRotationComposed Class Reference
#include <sot-core/rotation-simple.h>
Public Types
enum GivenRotationModifior {
GR_FIRST,
GR_SECOND,
GR_BOTH
}
Public Member Functions
sotRotationComposed (void)
sotRotationComposed (const sotRotationComposed &clone)
virtual ~sotRotationComposed (void)
template<typename TemplateRotation >
void pushBack (const TemplateRotation &R)
void pushBack (const sotRotationSimpleGiven &R)
void pushBack (const sotRotationSimpleHouseholder &R)
void pushBack (const RotationSimple *R)
void pushBack (const sotRotationComposed &R)
void popBack (void)
void clear (void)
template<typename bubTemplateMatrix >
void householderQRinit (const bubTemplateMatrix &RQ, const bubVector &betas, const int nbVector=-1)
void resetGRindex (const GivenRotationModifior modifior, const unsigned int k1, const unsigned int k2=1)
void increaseGRindex (const GivenRotationModifior modifior, const unsigned int k1, const unsigned int k2=1)
template<typename bubTemplateVector >
void multiplyRightVectorTemplate (bubTemplateVector &v) const
template<typename bubTemplateVector >
void multiplyLeftVectorTemplate (bubTemplateVector &v) const
template<typename bubTemplateMatrix >
void multiplyRightMatrixTemplate (bubTemplateMatrix &M) const
template<typename bubTemplateMatrix >
void multiplyLeftMatrixTemplate (bubTemplateMatrix &M) const
template<typename bubTemplateMatrix >
void multiplyRightTransposeMatrixTemplate (bubTemplateMatrix &M) const
template<typename bubTemplateMatrix >
void multiplyLeftTransposeMatrixTemplate (bubTemplateMatrix &M) const
template<typename bubTemplate >
void multiplyLeftTemplate (bubTemplate &Rx) const
template<typename bubTemplate >
void multiplyRightTemplate (bubTemplate &Rx) const
template<typename bubTemplate >
void multiplyLeftTransposeTemplate (bubTemplate &Rx) const
template<typename bubTemplate >
void multiplyRightTransposeTemplate (bubTemplate &Rx) const
virtual std::ostream & display (std::ostream &os) const
template<typename bubTemplateMatrix >
void householderTrigonalisation (bubTemplateMatrix &R)
template<typename bubTemplateMatrix >
void regularizeRankDeficientTriangle (bubTemplateMatrix &Rx, const unsigned int xn=0)
template<typename bubTemplateMatrix >
void regularizeRankDeficientTriangle (bubTemplateMatrix &Rx, bub::indirect_array<> orderCol, const unsigned int xn)
Public Attributes
std::list< RotationSimple * > listRotationSimple
std::list
< sotRotationSimpleHouseholder > listHouseholder
std::list< sotRotationSimpleGiven > listGivenRotation
Member Enumeration Documentation
enum sotRotationComposed::GivenRotationModifior
Enumerator:
GR_FIRST
GR_SECOND
GR_BOTH
Constructor & Destructor Documentation
sotRotationComposed::sotRotationComposed (void) [inline]
sotRotationComposed::sotRotationComposed (const sotRotationComposed & clone) [inline]
virtual sotRotationComposed::~sotRotationComposed (void) [inline, virtual]
References clear().
Member Function Documentation
void sotRotationComposed::clear (void) [inline]
Referenced by ~sotRotationComposed().
virtual std::ostream& sotRotationComposed::display (std::ostream & os) const [inline, virtual]
Implements RotationSimple.
template<typename bubTemplateMatrix > void sotRotationComposed::householderQRinit (const bubTemplateMatrix & RQ, const bubVector & betas, const int nbVector = -1) [inline]
Referenced by sotRotationComposedInExtenso::householderQRinit().
template<typename bubTemplateMatrix > void sotRotationComposed::householderTrigonalisation (bubTemplateMatrix & R) [inline]
References sotRotationSimpleHouseholder::householderExtraction().
void sotRotationComposed::increaseGRindex (const GivenRotationModifior modifior, const unsigned int k1, const unsigned int k2 = 1) [inline]
template<typename bubTemplateMatrix > void sotRotationComposed::multiplyLeftMatrixTemplate (bubTemplateMatrix & M) const [inline]
template<typename bubTemplate > void sotRotationComposed::multiplyLeftTemplate (bubTemplate & Rx) const [inline]
template<typename bubTemplateMatrix > void sotRotationComposed::multiplyLeftTransposeMatrixTemplate (bubTemplateMatrix & M) const [inline]
template<typename bubTemplate > void sotRotationComposed::multiplyLeftTransposeTemplate (bubTemplate & Rx) const [inline]
template<typename bubTemplateVector > void sotRotationComposed::multiplyLeftVectorTemplate (bubTemplateVector & v) const [inline]
template<typename bubTemplateMatrix > void sotRotationComposed::multiplyRightMatrixTemplate (bubTemplateMatrix & M) const [inline]
template<typename bubTemplate > void sotRotationComposed::multiplyRightTemplate (bubTemplate & Rx) const [inline]
template<typename bubTemplateMatrix > void sotRotationComposed::multiplyRightTransposeMatrixTemplate (bubTemplateMatrix & M) const [inline]
template<typename bubTemplate > void sotRotationComposed::multiplyRightTransposeTemplate (bubTemplate & Rx) const [inline]
template<typename bubTemplateVector > void sotRotationComposed::multiplyRightVectorTemplate (bubTemplateVector & v) const [inline]
void sotRotationComposed::popBack (void) [inline]
void sotRotationComposed::pushBack (const sotRotationSimpleGiven & R) [inline]
void sotRotationComposed::pushBack (const RotationSimple * R) [inline]
template<typename TemplateRotation > void sotRotationComposed::pushBack (const TemplateRotation & R) [inline]
void sotRotationComposed::pushBack (const sotRotationComposed & R) [inline]
References listRotationSimple.
void sotRotationComposed::pushBack (const sotRotationSimpleHouseholder & R) [inline]
template<typename bubTemplateMatrix > void sotRotationComposed::regularizeRankDeficientTriangle (bubTemplateMatrix & Rx, bub::indirect_array<> orderCol, const unsigned int xn) [inline]
References sotDEBUG.
template<typename bubTemplateMatrix > void sotRotationComposed::regularizeRankDeficientTriangle (bubTemplateMatrix & Rx, const unsigned int xn = 0) [inline]
References sotRotationSimpleGiven::nullifyFromRight(), and sotRotationSimpleGiven::sinF.
void sotRotationComposed::resetGRindex (const GivenRotationModifior modifior, const unsigned int k1, const unsigned int k2 = 1) [inline]
Member Data Documentation
std::list< sotRotationSimpleGiven > sotRotationComposed::listGivenRotation
std::list< sotRotationSimpleHouseholder > sotRotationComposed::listHouseholder
std::list< RotationSimple* > sotRotationComposed::listRotationSimple
Referenced by pushBack().