sot-core: detail::circular_buffer< T > Class Template Reference
detail::circular_buffer< T > Class Template Reference
#include <sot-core/fir-filter.h>
Public Member Functions
circular_buffer ()
void push_front (const T &data)
void reset_capacity (size_t n)
void reset_capacity (size_t n, const T &el)
T & operator[] (size_t i)
size_t size () const
template<class T>
class detail::circular_buffer< T >
Constructor & Destructor Documentation
template<class T> detail::circular_buffer< T >::circular_buffer () [inline]
Member Function Documentation
template<class T> T& detail::circular_buffer< T >::operator[] (size_t i) [inline]
template<class T> void detail::circular_buffer< T >::push_front (const T & data) [inline]
Referenced by FIRFilter< sigT, coefT >::compute().
template<class T> void detail::circular_buffer< T >::reset_capacity (size_t n, const T & el) [inline]
template<class T> void detail::circular_buffer< T >::reset_capacity (size_t n) [inline]
Referenced by FIRFilter< sigT, coefT >::commandLine().
template<class T> size_t detail::circular_buffer< T >::size (void) const [inline]
Referenced by FIRFilter< sigT, coefT >::commandLine(), and FIRFilter< sigT, coefT >::compute().