dynamicgraph::sot::GainAdaptive Class Reference
dynamicgraph::sot::GainAdaptive Class Reference
#include <sot/core/gain-adaptive.hh>
Public Member Functions
virtual void display (std::ostream &os) const
virtual const std::string & getClassName (void) const
GainAdaptive (const std::string &name)
GainAdaptive (const std::string &name, const double &lambda)
GainAdaptive (const std::string &name, const double &valueAt0, const double &valueAtInfty, const double &tanAt0)
void init (void)
void init (const double &lambda)
void init (const double &valueAt0, const double &valueAtInfty, const double &tanAt0)
void initFromPassingPoint (const double &valueAt0, const double &valueAtInfty, const double &errorReference, const double &valueAtReference)
void forceConstant (void)
virtual void commandLine (const std::string &cmdLine, std::istringstream &cmdArgs, std::ostream &os)
Public Attributes
dg::SignalPtr< ml::Vector, int > errorSIN
dg::SignalTimeDependent
< double, int > gainSOUT
Static Public Attributes
static const double ZERO_DEFAULT
static const double INFTY_DEFAULT
static const double TAN_DEFAULT
static const std::string CLASS_NAME
Protected Member Functions
double & computeGain (double &res, int t)
Protected Attributes
double coeff_a
double coeff_b
double coeff_c
Constructor & Destructor Documentation
dynamicgraph::sot::GainAdaptive::GainAdaptive (const std::string & name)
dynamicgraph::sot::GainAdaptive::GainAdaptive (const std::string & name, const double & lambda)
dynamicgraph::sot::GainAdaptive::GainAdaptive (const std::string & name, const double & valueAt0, const double & valueAtInfty, const double & tanAt0)
Member Function Documentation
virtual void dynamicgraph::sot::GainAdaptive::commandLine (const std::string & cmdLine, std::istringstream & cmdArgs, std::ostream & os) [virtual]
Reimplemented from dynamicgraph::Entity.
double& dynamicgraph::sot::GainAdaptive::computeGain (double & res, int t) [protected]
virtual void dynamicgraph::sot::GainAdaptive::display (std::ostream & os) const [virtual]
Reimplemented from dynamicgraph::Entity.
void dynamicgraph::sot::GainAdaptive::forceConstant (void)
virtual const std::string& dynamicgraph::sot::GainAdaptive::getClassName (void) const [inline, virtual]
Implements dynamicgraph::Entity.
void dynamicgraph::sot::GainAdaptive::init (void) [inline]
References init().
Referenced by init().
void dynamicgraph::sot::GainAdaptive::init (const double & lambda) [inline]
References init().
Referenced by init().
void dynamicgraph::sot::GainAdaptive::init (const double & valueAt0, const double & valueAtInfty, const double & tanAt0)
void dynamicgraph::sot::GainAdaptive::initFromPassingPoint (const double & valueAt0, const double & valueAtInfty, const double & errorReference, const double & valueAtReference)
Member Data Documentation
const std::string dynamicgraph::sot::GainAdaptive::CLASS_NAME [static]
double dynamicgraph::sot::GainAdaptive::coeff_a [protected]
double dynamicgraph::sot::GainAdaptive::coeff_b [protected]
double dynamicgraph::sot::GainAdaptive::coeff_c [protected]
dg::SignalPtr<ml::Vector,int> dynamicgraph::sot::GainAdaptive::errorSIN
dg::SignalTimeDependent<double,int> dynamicgraph::sot::GainAdaptive::gainSOUT
const double dynamicgraph::sot::GainAdaptive::INFTY_DEFAULT [static]
const double dynamicgraph::sot::GainAdaptive::TAN_DEFAULT [static]
const double dynamicgraph::sot::GainAdaptive::ZERO_DEFAULT [static]