dynamicgraph::sot::FIRFilter< sigT, coefT > Class Template Reference
dynamicgraph::sot::FIRFilter< sigT, coefT > Class Template Reference
#include <sot/core/fir-filter.hh>
Public Member Functions
virtual const std::string & getClassName () const
std::string getDocString () const
FIRFilter (const std::string &name)
virtual ~FIRFilter ()
virtual sigT & compute (sigT &res, int time)
void resizeBuffer (const unsigned int &size)
unsigned int getBufferSize () const
void setElement (const unsigned int &rank, const coefT &coef)
coefT getElement (const unsigned int &rank) const
virtual void commandLine (const std::string &cmdLine, std::istringstream &cmdArgs, std::ostream &os)
Static Public Member Functions
static std::string getTypeName (void)
static void reset_signal (sigT &, const sigT &)
Public Attributes
SignalPtr< sigT, int > SIN
SignalTimeDependent< sigT, int > SOUT
Static Public Attributes
static const std::string CLASS_NAME
template<class sigT, class coefT>
class dynamicgraph::sot::FIRFilter< sigT, coefT >
Constructor & Destructor Documentation
template<class sigT, class coefT> dynamicgraph::sot::FIRFilter< sigT, coefT >::FIRFilter (const std::string & name) [inline]
References dynamicgraph::Entity::addCommand(), dynamicgraph::sot::FIRFilter< sigT, coefT >::getBufferSize(), dynamicgraph::sot::FIRFilter< sigT, coefT >::resizeBuffer(), dynamicgraph::Entity::signalRegistration(), dynamicgraph::sot::FIRFilter< sigT, coefT >::SIN, and dynamicgraph::sot::FIRFilter< sigT, coefT >::SOUT.
template<class sigT, class coefT> virtual dynamicgraph::sot::FIRFilter< sigT, coefT >::~FIRFilter () [inline, virtual]
Member Function Documentation
template<class sigT, class coefT> virtual void dynamicgraph::sot::FIRFilter< sigT, coefT >::commandLine (const std::string & cmdLine, std::istringstream & cmdArgs, std::ostream & os) [inline, virtual]
Reimplemented from dynamicgraph::Entity.
template<class sigT, class coefT> virtual sigT& dynamicgraph::sot::FIRFilter< sigT, coefT >::compute (sigT & res, int time) [inline, virtual]
References dynamicgraph::SignalPtr< class, class >::access(), dynamicgraph::sot::detail::circular_buffer< T >::push_front(), dynamicgraph::sot::FIRFilter< sigT, coefT >::reset_signal(), dynamicgraph::sot::FIRFilter< sigT, coefT >::SIN, and dynamicgraph::sot::detail::circular_buffer< T >::size().
template<class sigT, class coefT> unsigned int dynamicgraph::sot::FIRFilter< sigT, coefT >::getBufferSize () const [inline]
Referenced by dynamicgraph::sot::FIRFilter< sigT, coefT >::FIRFilter().
template<class sigT, class coefT> virtual const std::string& dynamicgraph::sot::FIRFilter< sigT, coefT >::getClassName (void) const [inline, virtual]
Implements dynamicgraph::Entity.
template<class sigT, class coefT> std::string dynamicgraph::sot::FIRFilter< sigT, coefT >::getDocString () const [inline, virtual]
Reimplemented from dynamicgraph::Entity.
template<class sigT, class coefT> coefT dynamicgraph::sot::FIRFilter< sigT, coefT >::getElement (const unsigned int & rank) const [inline]
Referenced by dynamicgraph::sot::command::GetElement< sigT, coefT >::doExecute().
template<class sigT, class coefT> static std::string dynamicgraph::sot::FIRFilter< sigT, coefT >::getTypeName (void) [inline, static]
template<class sigT, class coefT> static void dynamicgraph::sot::FIRFilter< sigT, coefT >::reset_signal (sigT & , const sigT &) [inline, static]
Referenced by dynamicgraph::sot::FIRFilter< sigT, coefT >::compute().
template<class sigT, class coefT> void dynamicgraph::sot::FIRFilter< sigT, coefT >::resizeBuffer (const unsigned int & size) [inline]
References dynamicgraph::sot::detail::circular_buffer< T >::reset_capacity().
Referenced by dynamicgraph::sot::FIRFilter< sigT, coefT >::FIRFilter().
template<class sigT, class coefT> void dynamicgraph::sot::FIRFilter< sigT, coefT >::setElement (const unsigned int & rank, const coefT & coef) [inline]
Referenced by dynamicgraph::sot::command::SetElement< sigT, coefT >::doExecute().
Member Data Documentation
template<class sigT, class coefT> const std::string dynamicgraph::sot::FIRFilter< sigT, coefT >::CLASS_NAME [static]
template<class sigT, class coefT> SignalPtr<sigT, int> dynamicgraph::sot::FIRFilter< sigT, coefT >::SIN
Referenced by dynamicgraph::sot::FIRFilter< sigT, coefT >::compute(), and dynamicgraph::sot::FIRFilter< sigT, coefT >::FIRFilter().
template<class sigT, class coefT> SignalTimeDependent<sigT, int> dynamicgraph::sot::FIRFilter< sigT, coefT >::SOUT
Referenced by dynamicgraph::sot::FIRFilter< sigT, coefT >::FIRFilter().