sot-core: Timer< T > Class Template Reference
Timer< T > Class Template Reference
#include <sot-core/timer.h>
Public Member Functions
virtual const std::string & getClassName (void) const
Timer (const std::string &name)
virtual void display (std::ostream &os) const
virtual void commandLine (const std::string &cmdLine, std::istringstream &cmdArgs, std::ostream &os)
Public Attributes
dg::SignalPtr< T, int > sigSIN
dg::SignalTimeDependent< T, int > sigSOUT
dg::Signal< double, int > timerSOUT
Static Public Attributes
static const std::string CLASS_NAME
Protected Member Functions
void plug (dg::Signal< T, int > &sig)
T & compute (T &t, const int &time)
double & getDt (double &res, const int &)
Protected Attributes
struct timeval t0 t1
double dt
Friends
Timer_EXPORT friend std::ostream & operator<< (std::ostream &os, const Timer< T > &timer)
template<class T>
class Timer< T >
Constructor & Destructor Documentation
template<class T > Timer< T >::Timer (const std::string & name) [inline]
References Timer< T >::getDt(), dynamicgraph::Signal< T, Time >::setFunction(), dynamicgraph::Entity::signalRegistration(), Timer< T >::sigSIN, Timer< T >::sigSOUT, sotDEBUGIN, sotDEBUGOUT, and Timer< T >::timerSOUT.
Member Function Documentation
template<class T > void Timer< T >::commandLine (const std::string & cmdLine, std::istringstream & cmdArgs, std::ostream & os) [inline, virtual]
Reimplemented from dynamicgraph::Entity.
References sotDEBUGIN, and sotDEBUGOUT.
template<class T > T& Timer< T >::compute (T & t, const int & time) [inline, protected]
References sotDEBUG, sotDEBUGIN, and sotDEBUGOUT.
template<class T > void Timer< T >::display (std::ostream & os) const [inline, virtual]
Reimplemented from dynamicgraph::Entity.
References Timer< T >::dt, and Timer< T >::sigSIN.
template<class T > virtual const std::string& Timer< T >::getClassName (void) const [inline, virtual]
Reimplemented from dynamicgraph::Entity.
template<class T > double& Timer< T >::getDt (double & res, const int &) [inline, protected]
Referenced by Timer< T >::Timer().
template<class T > void Timer< T >::plug (dg::Signal< T, int > & sig) [inline, protected]
Friends And Related Function Documentation
template<class T > Timer_EXPORT friend std::ostream& operator<< (std::ostream & os, const Timer< T > & timer) [friend]
Member Data Documentation
template<class T > const std::string Timer< T >::CLASS_NAME [static]
Reimplemented from dynamicgraph::Entity.
template<class T > double Timer< T >::dt [protected]
Referenced by Timer< T >::display().
template<class T > dg::SignalPtr<T,int> Timer< T >::sigSIN
Referenced by Timer< T >::display(), and Timer< T >::Timer().
template<class T > dg::SignalTimeDependent<T,int> Timer< T >::sigSOUT
Referenced by Timer< T >::Timer().
template<class T > struct timeval t0 Timer< T >::t1 [protected]
template<class T > dg::Signal<double,int> Timer< T >::timerSOUT
Referenced by Timer< T >::Timer().