sot-core: FIRFilter< sigT, coefT > Class Template Reference
FIRFilter< sigT, coefT > Class Template Reference
#include <sot-core/fir-filter.h>
Public Member Functions
virtual const std::string & getClassName () const
FIRFilter (const std::string &name)
virtual ~FIRFilter ()
virtual sigT & compute (sigT &res, int time)
virtual void commandLine (const std::string &cmdLine, std::istringstream &cmdArgs, std::ostream &os)
Static Public Member Functions
static std::string getTypeName (void)
static void reset_signal (sigT &, const sigT &)
Public Attributes
dg::SignalPtr< sigT, int > SIN
dg::SignalTimeDependent< sigT,
int > SOUT
Static Public Attributes
static const std::string CLASS_NAME
template<class sigT, class coefT>
class FIRFilter< sigT, coefT >
Constructor & Destructor Documentation
template<class sigT , class coefT > FIRFilter< sigT, coefT >::FIRFilter (const std::string & name) [inline]
References FIRFilter< sigT, coefT >::SIN, and FIRFilter< sigT, coefT >::SOUT.
template<class sigT , class coefT > virtual FIRFilter< sigT, coefT >::~FIRFilter () [inline, virtual]
Member Function Documentation
template<class sigT , class coefT > virtual void FIRFilter< sigT, coefT >::commandLine (const std::string & cmdLine, std::istringstream & cmdArgs, std::ostream & os) [inline, virtual]
References detail::circular_buffer< T >::reset_capacity(), and detail::circular_buffer< T >::size().
template<class sigT , class coefT > virtual sigT& FIRFilter< sigT, coefT >::compute (sigT & res, int time) [inline, virtual]
References detail::circular_buffer< T >::push_front(), FIRFilter< sigT, coefT >::reset_signal(), FIRFilter< sigT, coefT >::SIN, and detail::circular_buffer< T >::size().
template<class sigT , class coefT > virtual const std::string& FIRFilter< sigT, coefT >::getClassName (void) const [inline, virtual]
template<class sigT , class coefT > static std::string FIRFilter< sigT, coefT >::getTypeName (void) [inline, static]
template<class sigT , class coefT > static void FIRFilter< sigT, coefT >::reset_signal (sigT & , const sigT &) [inline, static]
Referenced by FIRFilter< sigT, coefT >::compute().
Member Data Documentation
template<class sigT , class coefT > const std::string FIRFilter< sigT, coefT >::CLASS_NAME [static]
template<class sigT , class coefT > dg::SignalPtr<sigT, int> FIRFilter< sigT, coefT >::SIN
Referenced by FIRFilter< sigT, coefT >::compute(), and FIRFilter< sigT, coefT >::FIRFilter().
template<class sigT , class coefT > dg::SignalTimeDependent<sigT, int> FIRFilter< sigT, coefT >::SOUT
Referenced by FIRFilter< sigT, coefT >::FIRFilter().